### ISSUE TITLE
Internal throttle of SMT updates

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#100]
As per a review on https://github.com/sillsdev/serval/pull/143, we should throttle SMT updates internal to the SMT model so not have to throttle them on the helper and let the client libraries implement a simpler client.

**Comment by Enkidu93** [comment]
@ddaspit @johnml1135 Question: We need to throttle the updates to the Serval-side revision, which is really the issue here, correct? I.e., the revision on the Serval side is being updated too frequently, so we can't rely on the long-polling technique without some throttling. As I understand it, under the hood, the revision is only updated by being incremented each time the build status is updated via the platform service's `UpdateBuildStatus`. For SMT, this is called via the `BuildProgress` class in Machine. Now, in that class, it looks as though - before my time - John had added logic that throttled updates to once per second. Is that throttling not working? Should it be throttled more there? Did you want it to be throttled elsewhere by some other means (say, on the Serval side)? Is this issue already closed and you didn't realize it? Thank you for your time.

**Comment by Enkidu93** [comment]
As discussed in today's meeting, this seems to be a non-issue. John previously fixed this.
