### ISSUE TITLE
Health check ClearML Health Check with status Unhealthy

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#133]
We continue to get a few of these each day.  Can we increase the threshold in which we call it unhealthy?  What is it now?  Can it be 5 minutes at least?

**Comment by Enkidu93** [comment]
Damien made the `HttpClient` for the health check use no retry, so that would explain the reappearance of the issue. @ddaspit, what was the rationale there? And what's the preferred movement forward? I can make it a singleton and make it yield unhealthy after so many failures in sequence or give it a retry policy?

**Comment by ddaspit** [comment]
At a certain point, the `ClearMLHealthCheck` was updated to use its own `HttpClient` instead of using the `ClearMLService`. This is when it stopped using a retry policy. In any case, we don't want to use a retry policy for health checks, because it would cause the health check endpoint to hang. We should update the `ClearMLHealthCheck` to work in a similar fashion to the `S3HealthCheck`.
