### ISSUE TITLE
Logging and Performance monitoring in Rancher

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#25]
Let's set it up and get:
* Unified logging for every crash
* Performance - see if memory or CPU is pinging too much
* Send summary emails each week

**Comment by javamonkey79** [comment]
Hey @johnml1135 a few questions:

1. For unified logging, are you thinking as simple as writing out the log to s3, or did you have something else in mind?
2. re performance, do we have any APM tooling setup, such as prometheus?

**Comment by johnml1135** [comment]
Since we use Rancher, we should likely use their main solutions.
* For logging, I would look into https://rancher.com/docs/rancher/v2.5/en/logging/.
* For performance monitoring: https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/
* I would contact Greg Mackay for details.  He would likely need to work with you to enable them and craft the best solution.

**Comment by ddaspit** [comment]
One thing to keep in mind is that logging will be the main way that we will be able to analyze performance, troubleshoot issues, and collect usage metrics. Having some way to feed our logs into something like ElasticSearch and Kibana would be useful. AWS has the [OpenSearch Service](https://aws.amazon.com/opensearch-service/), which might be a good option.

**Comment by javamonkey79** [comment]
@johnml1135 @ddaspit I spent a little bit of time reading on the provided links. 

For logging, Rancher has an out of the box solution. It just requires installing. I can try this out, but I wasn't sure if the dallas-rke cluster is ok to modify or not and also if I even permissions. Please let me know if it is ok to experiment on, or not. If not, I can try it out on minikube, but that is a bit different than the point and click rancher install. Finally, it looks like once rancher logging is installed, there are several different ways to configure where the logs are sent to. So, once the first step is done, I could check to see if the OpenSearch service is right. 

For monitoring, it turns out that Rancher just uses Prometheus, which is what I expected. I've worked with Prometheus before and it's pretty easy to setup. It will require installing the chart, to start with. It may also require adding metrics scraping functionality to the docker images, depending on what we need. Although, it looks like Rancher does provide some basic metrics monitoring (CPU, memory) out of the box. So, it's worth just installing that as well. 

Let me know when\if I have the go ahead to start installing stuff or what procedure I might need to go through to make that happen and I'll put some time in doing it.

**Comment by javamonkey79** [comment]
@johnml1135 this can be closed now I think
